#############################################################################
# Makefile for building: SX_3D_Widget
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  SX_3D_Widget.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile SX_3D_Widget.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/LIBRARYES/glm -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SX_3D_Widget1.0.0
DISTDIR = /home/ruslan/QtProjects/SX_3D_Widget/.tmp/SX_3D_Widget1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		SX_3D_Widget.cpp \
		SX_3D_Client.cpp qrc_resources.cpp \
		moc_SX_3D_Widget.cpp \
		moc_SX_3D_Client.cpp
OBJECTS       = main.o \
		SX_3D_Widget.o \
		SX_3D_Client.o \
		qrc_resources.o \
		moc_SX_3D_Widget.o \
		moc_SX_3D_Client.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SX_3D_Widget.pro SX_3D_Widget.h \
		SX_3D_Client.h \
		SX_Model.hpp \
		SX_Camera.hpp main.cpp \
		SX_3D_Widget.cpp \
		SX_3D_Client.cpp
QMAKE_TARGET  = SX_3D_Widget
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = SX_3D_Widget


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_SX_3D_Client.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SX_3D_Widget.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SX_3D_Widget.pro \
		resources.qrc
	$(QMAKE) -o Makefile SX_3D_Widget.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
SX_3D_Widget.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile SX_3D_Widget.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents SX_3D_Widget.h SX_3D_Client.h SX_Model.hpp SX_Camera.hpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp SX_3D_Widget.cpp SX_3D_Client.cpp $(DISTDIR)/
	$(COPY_FILE) --parents SX_3D_Client.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		fragment_shader.frag \
		wire_fragment.frag \
		vertex_shader.vert \
		container.jpg \
		Bdot.jpg
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_SX_3D_Widget.cpp moc_SX_3D_Client.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_SX_3D_Widget.cpp moc_SX_3D_Client.cpp
moc_SX_3D_Widget.cpp: SX_3D_Widget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ruslan/QtProjects/SX_3D_Widget -I/opt/LIBRARYES/glm -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include SX_3D_Widget.h -o moc_SX_3D_Widget.cpp

moc_SX_3D_Client.cpp: SX_3D_Client.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ruslan/QtProjects/SX_3D_Widget -I/opt/LIBRARYES/glm -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include SX_3D_Client.h -o moc_SX_3D_Client.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_SX_3D_Client.h
compiler_uic_clean:
	-$(DEL_FILE) ui_SX_3D_Client.h
ui_SX_3D_Client.h: SX_3D_Client.ui \
		SX_3D_Widget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic SX_3D_Client.ui -o ui_SX_3D_Client.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp SX_3D_Client.h \
		SX_3D_Widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

SX_3D_Widget.o: SX_3D_Widget.cpp SX_3D_Widget.h \
		SX_Camera.hpp \
		SX_Model.hpp \
		/opt/LIBRARYES/glm/glm/glm.hpp \
		/opt/LIBRARYES/glm/glm/detail/_fixes.hpp \
		/opt/LIBRARYES/glm/glm/fwd.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_int.hpp \
		/opt/LIBRARYES/glm/glm/detail/setup.hpp \
		/opt/LIBRARYES/glm/glm/simd/platform.h \
		/opt/LIBRARYES/glm/glm/detail/type_float.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_vec.hpp \
		/opt/LIBRARYES/glm/glm/detail/precision.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat.hpp \
		/opt/LIBRARYES/glm/glm/vec2.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_vec2.hpp \
		/opt/LIBRARYES/glm/glm/detail/_swizzle.hpp \
		/opt/LIBRARYES/glm/glm/detail/_swizzle_func.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_vec2.inl \
		/opt/LIBRARYES/glm/glm/vec3.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_vec3.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_vec3.inl \
		/opt/LIBRARYES/glm/glm/vec4.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_vec4.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_vec4.inl \
		/opt/LIBRARYES/glm/glm/detail/type_vec4_simd.inl \
		/opt/LIBRARYES/glm/glm/mat2x2.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat2x2.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat2x2.inl \
		/opt/LIBRARYES/glm/glm/detail/func_matrix.hpp \
		/opt/LIBRARYES/glm/glm/mat2x3.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat2x3.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat2x3.inl \
		/opt/LIBRARYES/glm/glm/mat2x4.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat2x4.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat2x4.inl \
		/opt/LIBRARYES/glm/glm/mat3x2.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat3x2.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat3x2.inl \
		/opt/LIBRARYES/glm/glm/mat3x3.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat3x3.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat3x3.inl \
		/opt/LIBRARYES/glm/glm/mat3x4.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat3x4.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat3x4.inl \
		/opt/LIBRARYES/glm/glm/mat4x2.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat4x2.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat4x2.inl \
		/opt/LIBRARYES/glm/glm/mat4x3.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat4x3.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat4x3.inl \
		/opt/LIBRARYES/glm/glm/mat4x4.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat4x4.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_mat4x4.inl \
		/opt/LIBRARYES/glm/glm/detail/type_mat4x4_simd.inl \
		/opt/LIBRARYES/glm/glm/detail/func_matrix.inl \
		/opt/LIBRARYES/glm/glm/geometric.hpp \
		/opt/LIBRARYES/glm/glm/detail/func_geometric.hpp \
		/opt/LIBRARYES/glm/glm/detail/func_geometric.inl \
		/opt/LIBRARYES/glm/glm/detail/func_exponential.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_vec1.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_vec1.inl \
		/opt/LIBRARYES/glm/glm/detail/func_exponential.inl \
		/opt/LIBRARYES/glm/glm/detail/func_vector_relational.hpp \
		/opt/LIBRARYES/glm/glm/detail/func_vector_relational.inl \
		/opt/LIBRARYES/glm/glm/detail/func_vector_relational_simd.inl \
		/opt/LIBRARYES/glm/glm/detail/_vectorize.hpp \
		/opt/LIBRARYES/glm/glm/detail/func_exponential_simd.inl \
		/opt/LIBRARYES/glm/glm/simd/exponential.h \
		/opt/LIBRARYES/glm/glm/detail/func_common.hpp \
		/opt/LIBRARYES/glm/glm/detail/func_common.inl \
		/opt/LIBRARYES/glm/glm/detail/func_common_simd.inl \
		/opt/LIBRARYES/glm/glm/simd/common.h \
		/opt/LIBRARYES/glm/glm/detail/func_geometric_simd.inl \
		/opt/LIBRARYES/glm/glm/simd/geometric.h \
		/opt/LIBRARYES/glm/glm/detail/func_matrix_simd.inl \
		/opt/LIBRARYES/glm/glm/simd/matrix.h \
		/opt/LIBRARYES/glm/glm/trigonometric.hpp \
		/opt/LIBRARYES/glm/glm/detail/func_trigonometric.hpp \
		/opt/LIBRARYES/glm/glm/detail/func_trigonometric.inl \
		/opt/LIBRARYES/glm/glm/detail/func_trigonometric_simd.inl \
		/opt/LIBRARYES/glm/glm/exponential.hpp \
		/opt/LIBRARYES/glm/glm/common.hpp \
		/opt/LIBRARYES/glm/glm/packing.hpp \
		/opt/LIBRARYES/glm/glm/detail/func_packing.hpp \
		/opt/LIBRARYES/glm/glm/detail/func_packing.inl \
		/opt/LIBRARYES/glm/glm/detail/type_half.hpp \
		/opt/LIBRARYES/glm/glm/detail/type_half.inl \
		/opt/LIBRARYES/glm/glm/detail/func_packing_simd.inl \
		/opt/LIBRARYES/glm/glm/matrix.hpp \
		/opt/LIBRARYES/glm/glm/vector_relational.hpp \
		/opt/LIBRARYES/glm/glm/integer.hpp \
		/opt/LIBRARYES/glm/glm/detail/func_integer.hpp \
		/opt/LIBRARYES/glm/glm/detail/func_integer.inl \
		/opt/LIBRARYES/glm/glm/detail/func_integer_simd.inl \
		/opt/LIBRARYES/glm/glm/simd/integer.h \
		/opt/LIBRARYES/glm/glm/gtc/matrix_transform.hpp \
		/opt/LIBRARYES/glm/glm/gtc/constants.hpp \
		/opt/LIBRARYES/glm/glm/gtc/constants.inl \
		/opt/LIBRARYES/glm/glm/gtc/matrix_transform.inl \
		/opt/LIBRARYES/glm/glm/gtx/quaternion.hpp \
		/opt/LIBRARYES/glm/glm/gtc/quaternion.hpp \
		/opt/LIBRARYES/glm/glm/gtx/quaternion.inl \
		/opt/LIBRARYES/glm/glm/gtx/norm.hpp \
		/opt/LIBRARYES/glm/glm/gtx/norm.inl \
		/opt/LIBRARYES/glm/glm/gtx/euler_angles.hpp \
		/opt/LIBRARYES/glm/glm/gtx/euler_angles.inl \
		/opt/LIBRARYES/glm/glm/gtx/compatibility.hpp \
		/opt/LIBRARYES/glm/glm/gtx/compatibility.inl \
		/opt/LIBRARYES/glm/glm/gtc/type_ptr.hpp \
		/opt/LIBRARYES/glm/glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SX_3D_Widget.o SX_3D_Widget.cpp

SX_3D_Client.o: SX_3D_Client.cpp SX_3D_Client.h \
		ui_SX_3D_Client.h \
		SX_3D_Widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SX_3D_Client.o SX_3D_Client.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_SX_3D_Widget.o: moc_SX_3D_Widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SX_3D_Widget.o moc_SX_3D_Widget.cpp

moc_SX_3D_Client.o: moc_SX_3D_Client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SX_3D_Client.o moc_SX_3D_Client.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

